# -*- coding: utf-8 -*-
"""Ds-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiYBtDs4gaKblUYdit4oRVIe411g3xnw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv('/amazon_products_sales_data_uncleaned.csv')
df

"""Data Cleaning"""

df.info()

df.describe()

df['title']=df['title'].astype(str)
df['rating']=df['rating'].astype(str).str[0:3]
df['rating']=df['rating'].astype(float)
df['rating']=df['rating'].fillna(np.mean(df['rating']))
df['number_of_reviews']=df['number_of_reviews'].astype(str).str.replace(',','').astype(float)
df['number_of_reviews']=df['number_of_reviews'].fillna(0)
df['current/discounted_price']=df['current/discounted_price'].astype(str).str.replace(',','').astype(float).fillna(0)
df.drop('is_best_seller',axis=1,inplace=True)

df['is_sponsored'].value_counts()

df['is_sponsored'] = df['is_sponsored'].replace({'Sponsored': 1, 'Organic': 0})
df['buy_box_availability']=df['buy_box_availability'].replace({'Add to cart':1}).fillna(0)
df['is_couponed'] = df['is_couponed'].apply(lambda x: 0 if 'No Coupon' in str(x).lower() else 1)
df['has_sustainability_badge'] = df['sustainability_badges'].apply(lambda x: 0 if pd.isna(x) or str(x).lower() in ['nan', 'none', ''] else 1)
df.drop('sustainability_badges',axis=1,inplace=True)
df['image_url'] = df['image_url'].astype(str)
df['product_url'] = df['product_url'].astype(str)
df['collected_at'] = pd.to_datetime(df['collected_at'], errors='coerce')
df['price_on_variant'] = df['price_on_variant'].astype(str).str.extract(r'([\d.]+)').astype(float).fillna(0)
df['bought_in_last_month'] = df['bought_in_last_month'].astype(str)
df['bought_in_last_month'] = (
    df['bought_in_last_month'].str.replace('bought in past month', '').str.replace('+', '').str.replace('K', '000').str.strip())
df['bought_in_last_month'] = pd.to_numeric(df['bought_in_last_month'], errors='coerce').fillna(0)
df['listed_price'] = df['listed_price'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
df['listed_price'] = pd.to_numeric(df['listed_price'], errors='coerce').fillna(0)
df['delivery_days'] = df['delivery_details'].astype(str).str.extract(r'(\d+)').astype(float)
df['delivery_days'] = df['delivery_days'].fillna(0)
df.drop('delivery_details',axis=1,inplace=True)
df['discount'] = df['listed_price'] - df['current/discounted_price']
df['review_score'] = df['number_of_reviews'] * df['rating']
df['has_coupon_or_discount'] = ((df['is_couponed'] == 1) | (df['discount'] > 0)).astype(int)

df.head(20)

numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <=(upper_bound))]

"""Data Visualization"""

#Couponed vs Bought in last month
sns.boxplot(x='is_couponed', y='bought_in_last_month', data=df)
plt.xlabel('Couponed (0=No, 1=Yes)')
plt.ylabel('Bought in Last Month')
plt.title('Couponed vs Bought in Last Month')
plt.show()

"""Insights- Coupons drives sales.   

Use coupons strategically for boosting sales of low-selling products.
"""

#Discount vs Bought in last month
sns.scatterplot(x='discount', y='bought_in_last_month', alpha=0.3, data=df)
plt.xlabel('Discount')
plt.ylabel('Bought in Last Month')
plt.title('Discount vs Bought in Last Month')
plt.show()

"""Insights- Discounts do increase sales.

Focus discount strategy on mid-range discount products for maximum sales uplift.
"""

#Listed Price vs Price on Variant
sns.scatterplot(x='listed_price', y='price_on_variant', data=df)
plt.xlabel('Listed Price')
plt.ylabel('Price on Variant')
plt.title('Listed Price vs Price on Variant')
plt.show()

"""Insights- Variant pricing is proportional to base price, so higher-end products have proportionally expensive

Ensure consistent pricing strategy for variants; avoid zero/incorrect listed prices.
"""

#Sustainability Badge vs Rating
sns.boxplot(x='has_sustainability_badge', y='rating', data=df)
plt.xlabel('Sustainability Badge (0=No, 1=Yes)')
plt.ylabel('Rating')
plt.title('Sustainability Badge vs Rating')
plt.show()

"""Insights-Sustainability badges slightly positively influence rating

Marketing can highlight sustainability as added value, even if it doesn’t hugely affect sales.
"""

#Buy Box Availability vs Couponed
sns.countplot(x='buy_box_availability', hue='is_couponed', data=df)
plt.xlabel('Buy Box Availability (0=No,1=Yes)')
plt.ylabel('Count of Products')
plt.title('Buy Box vs Couponed')
plt.show()

"""Insights-Products in buy box are slightly more likely to have coupons, indicating sellers may use coupons to secure buy box.

Use coupon strategy to improve chances of winning the buy box.
"""

#Rating(bins) vs Bought in last month
df['rating_bin'] = pd.cut(df['rating'], bins=[0,3,4,4.5,5])
sns.boxplot(x='rating_bin', y='bought_in_last_month', data=df)
plt.xlabel('Rating Bins')
plt.ylabel('Bought in Last Month')
plt.title('Sales Distribution by Rating Bins')
plt.show()

"""Insights- Higher rated products tend to sell more.

Focus marketing, visibility, and stock management on products rated 4.5 and above, as they consistently drive the highest sales.

Model Training
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df[['rating','number_of_reviews','current/discounted_price','price_on_variant','listed_price', 'is_sponsored','is_couponed','buy_box_availability',
        'has_sustainability_badge', 'delivery_days','discount','review_score', 'has_coupon_or_discount']]
y = np.log1p(df['bought_in_last_month'])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Standardized Data:\n", X_scaled)

from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
model = LinearRegression()
rfe = RFE(estimator=model, n_features_to_select=9)
rfe.fit(X_scaled, y)
selected_features = X.columns[rfe.support_]
print("Selected Features:", selected_features)
X = X_scaled[:, rfe.support_]

X_train , X_test , y_train , y_test = train_test_split(X_scaled , y , test_size = 0.3 , random_state = 41)

X_train

y_train

X_test

y_test

"""Linear Regression"""

from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error:",mse)
print(f"R^2 Score:",r2)

"""Ridge Regression"""

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
ridge = Ridge()
param_grid = {'alpha': [0.1, 1, 10, 50, 100]}

ridge_cv = GridSearchCV(ridge, param_grid, cv=5, scoring='r2')
ridge_cv.fit(X_train, y_train)

best_alpha_ridge = ridge_cv.best_params_['alpha']
print("Best alpha for Ridge:", best_alpha_ridge)

y_pred_ridge = ridge_cv.predict(X_test)

mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print(f"Ridge Regression Results:\nMSE: {mse_ridge}\nR^2 Score: {r2_ridge}")

"""Lasso Regression"""

from sklearn.linear_model import Lasso
lasso = Lasso(max_iter=10000)
param_grid = {'alpha': [0.001, 0.01, 0.1, 1, 10]}

lasso_cv = GridSearchCV(lasso, param_grid, cv=5, scoring='r2')
lasso_cv.fit(X_train, y_train)

best_alpha_lasso = lasso_cv.best_params_['alpha']
print("Best alpha for Lasso:", best_alpha_lasso)

y_pred_lasso = lasso_cv.predict(X_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print(f"Lasso Regression Results:\nMSE: {mse_lasso}\nR^2 Score: {r2_lasso:}")

df.to_csv('dstask-3.csv')