# -*- coding: utf-8 -*-
"""DS TASK-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Pl_vhWntZRtXtpSHCH9dIZTd6PgF36M
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv('/merged.csv')
df

"""Data Cleaning"""

df.info()

df.describe()

df.tail()

df.duplicated().sum()

df=df.rename(
    columns={
        's':'speed',
        'a':'acceleration',
        'dir':'direction',
        'o':'orientation'
    }
)

df.drop(columns=['game_id', 'play_id', 'nfl_id', 'player_name','player_to_predict'], inplace=True)

df['player_position'].value_counts()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['player_position']=le.fit_transform(df['player_position'])

df['play_direction'].value_counts()

df['play_direction']=df['play_direction'].replace({'right':1,'left':0})

df['player_side'].value_counts()

df['player_side']=df['player_side'].replace({'Defense':1,'Offense':0})

df['player_role'].value_counts()

df['player_role']=df['player_role'].replace({'Defensive Coverage':1,'Targeted Receiver':0})

df['player_height'] = df['player_height'].astype(str).str.split('-', expand=True).astype(int).dot([12, 1])

df['player_birth_date'] = pd.to_datetime(df['player_birth_date'])
today = pd.Timestamp.today()
df['player_age'] = (today - df['player_birth_date']).dt.days // 365
df.drop(columns=['player_birth_date'], inplace=True)

df

"""Data Visualization"""

plt.figure(figsize=(8,6))
cols = ['x_x','y_x','x_y','y_y','ball_land_x','ball_land_y','speed','acceleration']
sns.heatmap(df[cols].corr(), annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Heatmap of Key Movement Features")
plt.show()

numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <=(upper_bound))]

"""Removal of outliers"""

plt.figure(figsize=(8,5))
sns.scatterplot(x='x_x', y='x_y', data=df)
plt.title('x_x vs x_y')

#This shows a linear relationship between x_y and x_x thats is position before and after pass wrt x coordinate

plt.figure(figsize=(8,5))
sns.scatterplot(x='y_x', y='y_y', data=df)
plt.title('y_x vs y_y')
plt.show()
#This shows a linear relationship between y_x and y_y thats is position before and after pass wrt y coordinate

plt.figure(figsize=(12,5))
sns.scatterplot(x='ball_land_x', y='x_y', data=df)
plt.title('ball_land_x vs x_y')

sns.scatterplot(x='ball_land_y', y='y_y', data=df)
plt.title('ball_land_y vs y_y')
plt.show()

"""Model Training"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X=df[['frame_id','play_direction','absolute_yardline_number','player_height','player_weight','player_age','x_x','y_x','speed','acceleration','direction',
    'orientation','num_frames_output','ball_land_x', 'ball_land_y','player_position','player_side','player_role'
]]
y=df[['x_y','y_y']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Standardized Data:\n", X_scaled)

X_train , X_test , y_train , y_test = train_test_split(X_scaled , y , test_size = 0.3 , random_state = 41)

X_train

y_train

X_test

y_test

"""Linear Regression"""

from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error:",mse)
print(f"R^2 Score:",r2)

"""Ridge Regression"""

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
ridge = Ridge()
param_grid = {'alpha': [0.1, 1, 10, 50, 100]}

ridge_cv = GridSearchCV(ridge, param_grid, cv=5, scoring='r2')
ridge_cv.fit(X_train, y_train)

best_alpha_ridge = ridge_cv.best_params_['alpha']
print("Best alpha for Ridge:", best_alpha_ridge)

y_pred_ridge = ridge_cv.predict(X_test)

mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print(f"Ridge Regression Results:\nMSE: {mse_ridge}\nR^2 Score: {r2_ridge}")

"""Lasso Regression"""

from sklearn.linear_model import Lasso
lasso = Lasso(max_iter=10000)
param_grid = {'alpha': [0.001, 0.01, 0.1, 1, 10]}

lasso_cv = GridSearchCV(lasso, param_grid, cv=5, scoring='r2')
lasso_cv.fit(X_train, y_train)

best_alpha_lasso = lasso_cv.best_params_['alpha']
print("Best alpha for Lasso:", best_alpha_lasso)

y_pred_lasso = lasso_cv.predict(X_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print(f"Lasso Regression Results:\nMSE: {mse_lasso}\nR^2 Score: {r2_lasso:}")

df.to_csv('dstask-2.csv')